### ISSUE TITLE
JWT Auth

### ISSUE THREAD

**Issue by SebastiaanKloos** [gpasztor87/oc-api-plugin#2]
Is it possible to use your JWT Auth plugin in this cool API plugin?

**Comment by gpasztor87** [comment]
Of course. I removed if from JWT depencencies, but you can use them together.
See: https://github.com/gpasztor87/oc-jwt-auth/commit/746fef92f96bb5c0e3177f0373d0f09266c7cf0d

**Comment by SebastiaanKloos** [comment]
That is not what I mean. Can I register JWT auth protected resources?

**Comment by gpasztor87** [comment]
Yes. In the generated controller you can register the jwt.auth middleware, like this:
```php
public function __construct()
{
    parent::__construct();

    $this->middleware('jwt.auth');
}

**Comment by SebastiaanKloos** [comment]
Thanks that will do the trick!

**Comment by SebastiaanKloos** [comment]
It looks like it is only working if you remove the `parent::__construct();`

**Comment by SebastiaanKloos** [comment]
I get an error when I pass in the token. Do you have any idea what I am doing wrong?
![screen shot 2016-12-22 at 23 07 40](https://cloud.githubusercontent.com/assets/6506510/21442039/b27faa0e-c89b-11e6-91e7-300e788c7815.png)

**Comment by SebastiaanKloos** [comment]
I got the error when I added the `public function __construct() {}` to my controller.

**Comment by SebastiaanKloos** [comment]
Changed it to:

use Illuminate\Http\Request;

public function __construct(Request $request)
{
    parent::__construct($request);

    $this->middleware('jwt.auth');
}

**Comment by gpasztor87** [comment]
Yes. You were right. Sorry, it was my mistake. I was distrait!
Thank you for the correction and enjoy my plugin.

Cheers!
